{
 "title": "skywatcher",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "airline",
    "label": "airline",
    "query": "SELECT DISTINCT airline FROM flight_logs ORDER BY 1"
   },
   {
    "name": "callsign",
    "label": "callsign",
    "query": "SELECT DISTINCT callsign \nFROM flight_logs \nWHERE airline IN (${airline:sqlstring}) \nORDER BY 1"
   }
  ]
 },
 "panels": [
  {
   "title": "flight path (select by airline)",
   "type": "geomap",
   "description": "운항중인 각 항공기들의 궤적",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "dataset": "skywatcher",
     "rawSql": "SELECT\n  created_at as \"time\",\n  airline,\n  callsign,\n  icao24,\n  lat,\n  lon,\n  velocity,\n  altitude\n  -- callsign 컬럼은 없으니까 SELECT에서 뺌\nFROM flight_logs\nWHERE\n  $__timeFilter(created_at)\n  AND airline IN (${airline:sqlstring})\n  AND callsign IN (${callsign:sqlstring}) \n  \n  -- 🔥 핵심: callsign 이름으로 검색하는 게 아니라,\n  -- 위에서 선택된 callsign에 해당하는 'icao24' ID로 검색하는 것!\n  -- AND icao24 IN (${icao_id:sqlstring})\n\nORDER BY created_at ASC"
    }
   ]
  },
  { "title": "geomap", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "속도별 geomap",
   "type": "geomap",
   "gridPos": { "h": 7, "w": 11, "x": 1, "y": 9 },
   "targets": [
    {
     "dataset": "skywatcher",
     "rawSql": "SELECT\n  updated_at as \"time\",\n  callsign,\n  airline,\n  lat,\n  lon,\n  velocity,\n  altitude\nFROM active_flights\nWHERE lat IS NOT NULL AND lon IS NOT NULL AND $__timeFilter(updated_at)"
    }
   ]
  },
  {
   "title": "항공사별 geomap",
   "type": "geomap",
   "gridPos": { "h": 7, "w": 11, "x": 12, "y": 9 },
   "targets": [
    {
     "dataset": "skywatcher",
     "rawSql": "SELECT\n  updated_at as \"time\",\n  callsign,\n  airline,\n  lat,\n  lon,\n  velocity,\n  altitude\nFROM active_flights\nWHERE lat IS NOT NULL AND lon IS NOT NULL AND $__timeFilter(updated_at)"
    },
    {
     "dataset": "skywatcher",
     "rawSql": "SELECT\n  updated_at as \"time\",\n  callsign,\n  airline,\n  lat,\n  lon,\n  velocity,\n  altitude\nFROM active_flights\nWHERE lat IS NOT NULL AND lon IS NOT NULL AND $__timeFilter(updated_at - INTERVAL '9 hours')"
    }
   ]
  },
  { "title": "daily stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "total flights",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 1, "y": 17 },
   "targets": [
    {
     "dataset": "skywatcher",
     "rawSql": "SELECT summary_date, total_flights FROM daily_stats;"
    }
   ]
  },
  {
   "title": "avg altitude",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 12, "y": 17 },
   "targets": [
    {
     "dataset": "skywatcher",
     "rawSql": "SELECT summary_date, avg_altitude FROM daily_stats;"
    }
   ]
  },
  {
   "title": "flight logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true
  },
  {
   "title": "flight logs",
   "type": "timeseries",
   "description": "airflow DAG 2가 제대로 작동되는지 확인하기 위함",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 25 },
   "targets": [
    {
     "dataset": "skywatcher",
     "rawSql": "SELECT \n    -- 'hour'를 'minute'으로 바꾸면 분 단위로도 볼 수 있어\n    date_trunc('hour', created_at) as \"시간\", \n    COUNT(*) as \"데이터 수\"\nFROM flight_logs\nGROUP BY 1\nORDER BY 1 DESC;"
    }
   ]
  }
 ]
}